### ISSUE TITLE
Failed to start selenium-standalone on Circleci

### ISSUE THREAD

**Issue by lttrung112** [webdriverio/selenium-standalone#565]
## Expected Behavior
Start selenium-standalone successfully

## Current Behavior
2021-10-09T04:44:04.954Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: not found: java
    at getNotFoundError (/home/circleci/project/node_modules/selenium-standalone/node_modules/which/which.js:10:17)
    at Function.whichSync [as sync] (/home/circleci/project/node_modules/selenium-standalone/node_modules/which/which.js:121:9)
    at start (/home/circleci/project/node_modules/selenium-standalone/lib/start.js:56:27)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at start (internal/util.js:296:12)
    at SeleniumStandaloneLauncher.onPrepare (/home/circleci/project/node_modules/@wdio/selenium-standalone-service/build/launcher.js:115:30)
    at /home/circleci/project/node_modules/@wdio/cli/build/utils.js:28:17
    at async Promise.all (index 0)
    at Launcher.run (/home/circleci/project/node_modules/@wdio/cli/build/launcher.js:94:13)

## Steps to Reproduce
1.  .config.yml

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.22.5
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run WebdirverIO tests
          command: |
            npm test ./tests/e2e/config/wdio.chrome.conf.js
          no_output_timeout: 30m
      - run:
          name: Run WebdirverIO tests
          command: |
            npm test ./tests/e2e/config/wdio.firefox.conf.js
          no_output_timeout: 30m
      - store_test_results:
          path: ./wdio-logs

      - store_artifacts:
          path: ./screenShots/

      - store_artifacts:
          path: ./errorShots/

2.  wdio.conf.js
    services: [
        ['selenium-standalone', {
            logPath: 'logs',
            installArgs: {
                drivers: {
                    chrome: { version: '94.0.4606.61' },
                    firefox: { version: '0.30.0' }
                }
            },
            args: {
                drivers: {
                    chrome: { version: '94.0.4606.61' },
                    firefox: { version: '0.30.0' }
                }
            },
        }]
    ],

## Logs
It is helpful to include any logs that selenium-standalone outputs to help diagnose issues.
Take a look at the [README](https://github.com/vvo/selenium-standalone/blob/master/README.md#debug-logs-for-selenium-standalone-process) for how
to enable debug log statements that will help us even more than the standard output logs.

If there are lots of logs, please link to [a public gist](https://gist.github.com/).

## Your Environment
* Version of `selenium-standalone` that you are using:     "@wdio/selenium-standalone-service": "^7.5.2",
* Is there another tool calling `selenium-standalone` on your behalf: No
* System/platform: MacOs
*  Wdio version:  "^7.5.2",

**Comment by christian-bromann** [comment]
> Error: not found: java

It seems that the image your pipeline runs has no Java support. Maybe worth checking for an image that has Java and Node.js installed. If you only run Chrome and Firefox I recommend to use the chromedriver and geckodriver services instead as they don't require Java to be installed.

Closing as this is a configuration issue. Happy to provide further advice.
