### ISSUE TITLE
Unable to execute scripts in Internet Explorer 11, Terminates with 'Timeout Exceeded' Error

### ISSUE THREAD

**Issue by Zarmeena** [webdriverio/selenium-standalone#566]
## Expected Behavior
Test scripts should run in Internet Explorer 11 (IE 11) browser. 

## Current Behavior
On triggering script execution in IE, the browser window is launched but no action happens (seems the window is freezed). After waiting for sometime, the execution terminates with 'Error: Timeout of 150000ms exceeded'. 
Have done the following set up for execution on IE:

- Enabled 'Protected Mode' for all the zones in 'Internet Options'
- Set  path: '/wd/hub' in WDIO runner

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

1.  Set up WDIO test runner
2.  Provide these details in the runner:
     path: '/wd/hub',
     services: ['selenium-standalone'],
       capabilities: [
			{
				browserName: 'internet explorer',
			        maxInstances: 1
			}],
3.  Invoke the test runner
4.  Ensure 'Protected Mode' is set for all the zones in 'Internet Options' of IE

## Logs
It is helpful to include any logs that selenium-standalone outputs to help diagnose issues.
Take a look at the [README](https://github.com/vvo/selenium-standalone/blob/master/README.md#debug-logs-for-selenium-standalone-process) for how
to enable debug log statements that will help us even more than the standard output logs.

If there are lots of logs, please link to [a public gist](https://gist.github.com/).

## Your Environment
* Version of `selenium-standalone` that you are using: "@wdio/selenium-standalone-service": "^7.8.0",
* Is there another tool calling `selenium-standalone` on your behalf: NO
* System/platform: Windows 10
* Other details that might be important:
**Using the following modules:
"@wdio/cli": "^7.9.0",
"@wdio/local-runner": "^7.9.0",
"@wdio/mocha-framework": "^7.9.0",
"selenium-webdriver": "4.0.0-alpha.5",

**Comment by christian-bromann** [comment]
Can you please provide all logs?

**Comment by Zarmeena** [comment]
I tried investigating and changed the IE driver as well, but the IE browser window seems unresponsive. Not sure why this is happening. Can you please advise some other way to debug this?

**Comment by udarrr** [comment]
I believe not necessary support IE anymore as it's fully deprecated since 2022, and can be run only under edge wrapping. I think it have sense also delete old edge from default config, but preserve some code for backward compatibility in project in case if someone would like to use it somewhere

**Comment by christian-bromann** [comment]
Good call @udarrr will close now.
