### ISSUE TITLE
Selenium server does not start in 8.0.4 version

### ISSUE THREAD

**Issue by sgauruseu** [webdriverio/selenium-standalone#582]
Simple standalone test,  unpack and read the `README.md`
[standalone-test.zip](https://github.com/webdriverio/selenium-standalone/files/7454230/standalone-test.zip)
```
run the test:
 ./gradlew standaloneTest

```

## Steps to Reproduce
1.  create a simple standalone test
2.  Specify in `package.json` the latest version of    `selenium-standalone: 8.0.4`
3.  Use the API for starting  the selenium server : https://github.com/webdriverio/selenium-standalone/blob/main/docs/API.md 

```
 await selenium.install({
            version: '3.141.59',
            baseURL: 'https://selenium-release.storage.googleapis.com',
            drivers: {
                chrome: {
                    version: driverVersion,
                    arch: process.arch,
                    baseURL: 'https://chromedriver.storage.googleapis.com'
                },
            }
        });
```
3.  start the selenium server  and run a test

**Issue** ; Error in console and test did not start

```
 Missing\node_modules\selenium-standalone\.selenium\selenium-server\4.0.0\selenium-server.jar
```

##  Environment
* Version of `selenium-standalone`   "selenium-standalone": 8.0.4
* System/platform: Windows, Linux
*   "webdriverio": "7.16.3",  Node - v12.16.3  selenium version - 3.141.59

**Comment by christian-bromann** [comment]
fixed in #590
