### ISSUE TITLE
Custom Port values not adhered to - always looking for node on 4444

### ISSUE THREAD

**Issue by abdul-farhat** [webdriverio/selenium-standalone#616]
## Expected Behavior
Change capabilities host and port to custom values as: 

```
  capabilities: [{
        maxInstances: 5,
 
        browserName: 'chrome',
        acceptInsecureCerts: true,

        hostname: '127.0.0.1',
        port: 4449,

        'goog:chromeOptions': {
            args: [
                '--disable-gpu',
                '--no-sandbox',
                '--disable-infobars',
                 '--headless',
                '--disable-features=VizDisplayCompositor',
                '--window-size=1920,1080',
            ]
        }
    }],
```

Services as:

```
    services: [
        ['selenium-standalone', {
            logPath: './temp',
            installArgs: {
                version: "3.141.59",
                drivers: {
                    chrome: { version: "97.0.4692.71" }
                }
            },
            args: {
                version: "3.141.59",
                seleniumArgs: ['-host', '127.0.0.1', '-port', '4449'],
                drivers: {
                    chrome: { version: "97.0.4692.71" },
                }
            },
        }]
    ] 
```
Expect standalone to create hub/node for 4444 and run tests.

## Current Behavior

Get the following regardless of port number:

`
Failed to connect to selenium. Attempts left: 25 
 connect ECONNREFUSED 127.0.0.1:4444
`

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

https://github.com/abdul-farhat/wdio-7-example

https://gitpod.io/#https://github.com/abdul-farhat/wdio-7-example

```
npm i

npm run e2e-chrome

```

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by tbaruah58-elsv** [comment]
What was the fix for this issue?
