### ISSUE TITLE
basePath documentation inconsistent with behavior

### ISSUE THREAD

**Issue by rnreekez** [webdriverio/selenium-standalone#631]
## Expected Behavior
This likely wouldn't impact most people, but the documentation for opts.basePath is inconsistent with the actual behavior.

[Documentation](https://github.com/webdriverio/selenium-standalone/blob/main/docs/API.md#seleniuminstallopts) states basePath default value is `process.cwd() + ".selenium"` while the programmed behavior is relative to [`__dirname`](https://github.com/webdriverio/selenium-standalone/blob/102dd8d78277942dc4f560129d2b340627498ef3/lib/compute-fs-paths.js#L5).

Like I said, most people wouldn't notice but I happen to have a project where `__dirname` and `process.cwd()` values are very different.

If desired, i can make the change if someone would let me know which to follow, meaning either the code is correct and the documentation needs updating or the documentation is correct and the code needs a fix.

**Comment by christian-bromann** [comment]
Thanks for reporting @rnreekez , mind opening a PR for it?

**Comment by rnreekez** [comment]
Hey @christian-bromann, no problem. Are we updating the docs or changing the code to adhere to the docs?

**Comment by christian-bromann** [comment]
In order to not get surprised let's update the docs and keep the implementation as is.
