### ISSUE TITLE
[🐛 Bug]: error in downloading selenium-standalone - Error in "getDownloadStream" #592

### ISSUE THREAD

**Issue by wyhmichael** [webdriverio/selenium-standalone#653]
### Have you read the Contributing Guidelines on issues?
 * [x]  I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).
 
 ### WebdriverIO Version
 latest
 
 ### Node.js Version
 latest
 
 ### Mode
 Standalone Mode
 
 ### Which capabilities are you using?
 ```ts
 {
             browserName: 'chrome',
             acceptInsecureCerts: true,
             'goog:chromeOptions': {
                 args: ['--headless', '--disable-gpu', "--no-sandbox", '--window-size=1280,800', '--disable-dev-shm-usage', '--disable-web-security']
 }
 
         installArgs: {
             version : "3.141.59",
             baseURL : "https://selenium-release.storage.googleapis.com",
             drivers : {
                 chrome : {
                     version : "95.0.4638.69",
                     arch    : process.arch,
                     baseURL : "https://chromedriver.storage.googleapis.com"
                 }
             }
         }
 ```
 
 ### What happened?
 from last few days, i started getting below error `Error in "getDownloadStream". Could not download https://selenium-release.storage.googleapis.com/selenium-3.141.59/selenium-server-standalone-3.141.59.jar 442See more details below: 443404 https://selenium-release.storage.googleapis.com/selenium-3.141.59/selenium-server-standalone-3.141.59.jar 444Response code 404 (Not Found)`
 
 the url seems invalid. correct url is https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar. how to change it? ` installArgs: { version : "3.141.59", baseURL : "https://selenium-release.storage.googleapis.com", drivers : { chrome : { version : "95.0.4638.69", arch : process.arch, baseURL : "https://chromedriver.storage.googleapis.com" } } },`
 
 ### What is your expected behavior?
 selenium should be downloaded without any issues.
 
 ### How to reproduce the bug.
 start tests with the below config
 ```
 config.services = [
      [
        'selenium-standalone',
        {
          logPath: 'logs/selenium',
          installArgs: {
              version: '3.141.59',
              baseURL: 'https://selenium-release.storage.googleapis.com'
              chrome: {
                version: '99.0.4844.51',
                arch: process.arch,
                baseURL: 'https://chromedriver.storage.googleapis.com'
              }
          },
          watchMode: true,
          args: {
            version: '3.141.59',
            baseURL: 'https://selenium-release.storage.googleapis.com'
            chrome: {
                version: '99.0.4844.51',
                arch: process.arch,
                baseURL: 'https://chromedriver.storage.googleapis.com'
            }
          }
        }
      ]
    ]
 ```
 ### Relevant log output
 ```ts
Error in "Could not request headers from https://selenium-release.storage.googleapis.com/selenium-3.141.59/selenium-server-standalone-3.141.59.jar: 404, continue without checking for latest version.".
 ```
 
 ### Code of Conduct
 * [x]  I agree to follow this project's Code of Conduct
 
 ### Is there an existing issue for this?
 * [x]  I have searched the existing issues

**Comment by wyhmichael** [comment]
seems like there's a regression : https://github.com/webdriverio/selenium-standalone/issues/592

**Comment by christian-bromann** [comment]
Thanks for reporting!

Would you like to help and look into this?

**Comment by wyhmichael** [comment]
kk, I'll see what I can do

**Comment by wyhmichael** [comment]
Hi @christian-bromann I made PR for this - https://github.com/webdriverio/selenium-standalone/pull/654, please take a look
