### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by gauravgandhi1315** [webdriverio/selenium-standalone#661]
Updated my node version to 16 and selenium-standalone was successfully installed. When I run my tests, I see this issue:

      cb(new Error("Could not request headers from " + url + ": " + err));
      ^
Error: Callback was already called

@wdio/selenium-standalone-service": "6.1.14"
"selenium-standalone": "6.20.1"

Can someone please help?

**Comment by udarrr** [comment]
It has been resolved in v6.21.0 https://github.com/webdriverio/selenium-standalone/releases/tag/v6.21.0 by replacing 'request' to 'got'
