### ISSUE TITLE
[🐛 Bug]: <title>404 https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip Response code 404 (Not Found)

### ISSUE THREAD

**Issue by misjorge** [webdriverio/selenium-standalone#674]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.6.0

### Node.js Version

13.8.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      maxInstances: 1,

      browserName: "chrome",
      "goog:chromeOptions": {
        args: ["--disable-gpu"],
        // args: ["--headless", "--disable-gpu"]
      }
```

### What happened?

Immediately after started running the test, the following error appeared:

022-02-13T08:56:39.605Z INFO @wdio/cli:launcher: Run onPrepare hook
Start launch 30dxt8aokzl1a01q
Error in "getDownloadStream". Could not download https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip
See more details below:
404 https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip
Response code 404 (Not Found)

Ended WebDriver sessions gracefully after a SIGINT signal was received!

### What is your expected behavior?

Test should run as before

### How to reproduce the bug.

just install the following, and run the test:

"devDependencies": {
    "@types/node": "15.6.0",
    "@wdio/cli": "7.6.0",
    "@wdio/cucumber-framework": "7.6.0",
    "@wdio/devtools-service": "7.6.0",
    "@wdio/local-runner": "7.6.0",
    "@wdio/selenium-standalone-service": "7.10.1",
    "@wdio/spec-reporter": "7.6.0",
    "@wdio/sync": "7.6.0",
    "chai": "*",
    "husky": "^4.2.3",
    "lint-staged": "^10.1.1",
    "prettier": "^2.0.2",
    "tslint": "^6.1.0",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "4.2.4",
    "wdio-reportportal-reporter": "6.4.1",
    "wdio-reportportal-service": "6.4.1"
  },
  "dependencies": {
    "@types/chai": "4.2.18",
    "commander": "5.0.0",
    "moment": "^2.24.0",
    "request-promise": "^4.2.6",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "winston": "^3.2.1"
  },

### Relevant log output

```typescript
2022-02-13T08:56:39.605Z INFO @wdio/cli:launcher: Run onPrepare hook
Start launch 30dxt8aokzl1a01q
Error in "getDownloadStream". Could not download https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip
See more details below:
404 https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip
Response code 404 (Not Found)


Ended WebDriver sessions gracefully after a SIGINT signal was received!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by udarrr** [comment]
For edge chromium has been set version by default like 117.0.2045.55 in the pr https://github.com/webdriverio/selenium-standalone/pull/851 that contain all platform executable files
