### ISSUE TITLE
[Bug]: Error in "getDownloadStream". Could not download zip file | M1 MacBooks

### ISSUE THREAD

**Issue by ghopkins-legacy** [webdriverio/selenium-standalone#709]
## Expected Behavior

getDownloadStream downloads the correct chromdriver for M1 MacBooks.

ChromeDriver changed their zip file naming convention for M1 MacBooks. 

Previous: chromedriver_mac64_m1.zip
https://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.21/

Current: chromedriver_mac_arm64.zip
https://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.61/

Other people with this issue. 
https://groups.google.com/g/chromedriver-users/c/JRuQzH3qr2c

## Current Behavior
getDownloadStream cannot download due to zip file name change. 

Error returned:
See more details below:
404 https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
Response code 404 (Not Found)

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include commands that you used
in the shell, or snippets of how you are using the JavaScript API.

1.  Have a M1 MacBook
2.  Run npm update selenium-standalone or npm install selenium-standalone on an existing project
3.  Run a test case 

## Error

Error in "getDownloadStream". Could not download https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
See more details below:
404 https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
Response code 404 (Not Found)
  ✖ "before all" hook: codeceptjs.beforeSuite for "test case" 

If there are lots of logs, please link to [a public gist](https://gist.github.com/).

## Your Environment
* Version of `selenium-standalone` that you are using: 8.2.0
* Is there another tool calling `selenium-standalone` on your behalf: codeceptjs - version: 3.1.1
* System/platform: M1 MacBooks

**Comment by christian-bromann** [comment]
Thanks for reporting!

We should update the download path for Chromedriver.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by Ghop11** [comment]
@christian-bromann Created a PR for this issue. https://github.com/webdriverio/selenium-standalone/pull/710

**Comment by christian-bromann** [comment]
Thank you, let's continue convo in #710

**Comment by thiago-luppi-td** [comment]
Is this issue been resolved? Because It happened to me with the last chrome update: Version 107.0.5304.87 (Official Build) (arm64). I'm trying to download the following CHROMEDRIVER=107.0.5304.62 but I'm getting the same error:

Error in "getDownloadStream". Could not download https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip
See more details below:
404 https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip
Response code 404 (Not Found)



It is trying to download from this url: https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip
When the file lies in here: https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac_arm64.zip

**Comment by chris7716** [comment]
@thiago-luppi-td  Were you able to resolve this one? I am having the same issue.

**Comment by thiago-luppi-td** [comment]
> @thiago-luppi-td Were you able to resolve this one? I am having the same issue.

Yeah. I had to overwrite the line 117 of the following:
node_modules/lib/compute-download-urls.js

117:
remove that: platform = 'mac64' + (process.arch === 'arm64' ? '_m1' : '');
add this: platform = process.arch === 'arm64' ? 'mac_arm64' : 'mac64';

This is the fix they provided, but for some reason I couldnt get by updating. This should do the job.

**Comment by yuriibazhan** [comment]
Hi, having the same issue 404 https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64_m1.zip
