### ISSUE TITLE
Unable to download latest Chrome MacOS M1 webdriver

### ISSUE THREAD

**Issue by arctouch-thiagowerner** [webdriverio/selenium-standalone#725]
## Expected Behavior
Package should handle Chrome MacOS M1 webdriver.

## Current Behavior
Package expects chromedriver_mac64_m1.zip but they changed the name to: chromedriver_mac_arm64.zip

## Steps to Reproduce
1.  Add the capabilities: ['selenium-standalone', { drivers: { firefox: 'latest', chrome: 'latest' } }]
2. Run the code

## Logs
```
Error in "getDownloadStream". Could not download https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip
See more details below:
404 https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip
Response code 404 (Not Found)
/Users/thiagowerner/webdriverio_boilerplate/node_modules/selenium-standalone/lib/install.js:292
          throw new Error('Could not download ' + downloadUrl);
```

## Your Environment
* Version of `selenium-standalone` that you are using: 7.21.0
* System/platform: MacOS M1 Pro

**Comment by roggerrouse** [comment]
A workaround is using `fullURL` parameter, such as:
```
  chrome: {
    fullURL: 'https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac_arm64.zip'
  },
```

**Comment by Joosakur** [comment]
When using this through webdriverio that workaround doesn't work, I think, but I've had to manually change version in node_modules/selenium-standalone/lib/default-config.js to some older one which has the old naming scheme.

**Comment by djom202** [comment]
I've the same issue with the version 108.0.5359.71/chromedriver_mac64_m1.zip, and I tried to download a previous version and pasted another different version there but the tests never started to run, just is keeping in `Execution of 1 workers started at 2022-12-02T15:10:20.079Z` until end the process.

**Comment by lebedenko-vyacheslav** [comment]
have the same problem with M1. Solution with fullURL didn't have me

**Comment by udarrr** [comment]
It's been resolved since v9
