### ISSUE TITLE
Unable to run test cases in firefox using selenium standalone server 

### ISSUE THREAD

**Issue by RangaPavan225** [webdriverio/selenium-standalone#830]
With the @wdio/selenium-standalone v8.14.0, running firefox test cases results in following error and can be seen in logs.

> wdio firefox config
<img width="520" alt="image" src="https://github.com/webdriverio/selenium-standalone/assets/98270054/57547d0c-a2a1-4c87-bbc9-c2782c49b733">

> package. json file 
<img width="381" alt="image" src="https://github.com/webdriverio/selenium-standalone/assets/98270054/d46b4d74-afb6-4289-94f4-7b2068450354">

> error log
2023-08-21T10:27:06.656Z WARN @wdio/config:ConfigParser: pattern ./test/specs/**/*.js did not match any file
2023-08-21T10:27:06.688Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/selenium-standalone-service".
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

**Comment by udarrr** [comment]
Issue not related to functionality the package
