### ISSUE TITLE
The downloaded webdrivers filename should include [.exe] file extension on windows 

### ISSUE THREAD

**Issue by humphreyn** [webdriverio/selenium-standalone#843]
## Expected Behaviour

The drivers for Chrome, MS Edge and Firefox (Gecko)  webdrivers filename should include the [.exe] file extension on windows. 

| Actual File name    | Expected File name |
|---------------------|-----------------------|
| chromedriver         | chomedriver.exe      |
| msedgedriver         | msedgedriver.exe    |
| geckodriver            | geckodriver.exe       |

## Current Behaviour
The filenames for Chrome, MS Edge and Firefox (Gecko)  webdrivers do not have an extension.
The actual zip files containing the webdriver does correctly have the .exe file extension but the uncompressing process removes the extension.

## Steps to Reproduce
All steps below on Windows 11

1.  npm install selenium-standalone -g
2.  selenium-standalone install

## Logs

`----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.9.0/selenium-server-4.9.0.jar
to: C:\Users\humphreyn\AppData\Roaming\nvm\v16.18.0\node_modules\selenium-standalone\.selenium\selenium-server\4.9.0\selenium-server.jar
---
chrome install:
from: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win32/chromedriver-win32.zip
to: C:\Users\humphreyn\AppData\Roaming\nvm\v16.18.0\node_modules\selenium-standalone\.selenium\chromedriver\latest-win32\chromedriver
---
ie install:
from: https://selenium-release.storage.googleapis.com/3.150/IEDriverServer_x64_3.150.1.zip
to: C:\Users\humphreyn\AppData\Roaming\nvm\v16.18.0\node_modules\selenium-standalone\.selenium\iedriver\3.150.1-win32\IEDriverServer.exe
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win64.zip
to: C:\Users\humphreyn\AppData\Roaming\nvm\v16.18.0\node_modules\selenium-standalone\.selenium\geckodriver\latest-win32\geckodriver
---
edge install:
from: https://download.microsoft.com/download/F/8/A/F8AF50AB-3C3A-4BC4-8773-DC27B32988DD/MicrosoftWebDriver.exe
to: C:\Users\humphreyn\AppData\Roaming\nvm\v16.18.0\node_modules\selenium-standalone\.selenium\edgedriver\17134\MicrosoftEdgeDriver.exe
---
chromiumedge install:
from: https://msedgedriver.azureedge.net/116.0.1938.76/edgedriver_win64.zip
to: C:\Users\humphreyn\AppData\Roaming\nvm\v16.18.0\node_modules\selenium-standalone\.selenium\chromiumedgedriver\latest-win32\msedgedriver

[====] 100%      https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win32/chromedriver-win32.zip

[=========] 100%      https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.9.0/selenium-server-4.9.0.jar

-----
selenium-standalone installation finished
-----`

## Your Environment
* selenium-standalone v9.1.1
* Is there another tool calling `selenium-standalone` on your behalf: No
* System/platform: MS Windows 11 Enterprise / Version 10.0.22621 Build 22621
* NPM v8.19.2
* Node  v16.18.0

**Comment by udarrr** [comment]
Hi @humphreyn I'm curious about execution. Would you like to start it without selenium-server, because selenium-server can execute the drivers without extension.

**Comment by humphreyn** [comment]
Hi @udarrr ,
Sorry I should have been more specific. We use NightwatchJs along with CucumberJs  as our testing framework.

Now as stated in the SeleniumHQ repo instructions we do not use selenium-standalone/server when running locally as it acts as a proxy between our scripts and the browser drivers and adds an extra hop for each request and does slow things down.

We only use the selenium-standalone/server when connecting to a browser on a remote host i.e. in a Grid.

So to your point, IMO I do not think that you should be removing the ".exe" extension or changing the name of the file when unzipping as it will and does break frameworks that create browser sessions without using the selenium-standalone/server.

I have also noticed that the options.baseURL is ignored when a version is specified that is >=15, though not when stipulated as "latest". As I am behind a company firewall we temporarily want to use http instead of https to download the drivers until we resolve the "get local issuer certificate" issue

**Comment by udarrr** [comment]
Hi @humphreyn, Yes it have sense, currently 'install' return all installed paths we can use the path for starting drivers, but the tool still downloading and installing selenium-server and for the cases it would be great prevent selenium-server from the actions. Also regarding options.baseURL i am still confusing options.baseURL is selenium server base url what's wrong with it?

**Comment by udarrr** [comment]
fixed in https://github.com/webdriverio/selenium-standalone/pull/848
