### ISSUE TITLE
Axios vulnerability fixed and merged but not released in new version

### ISSUE THREAD

**Issue by tuortheblessed** [webdriverio/selenium-standalone#869]
Getting the same issue as in #859 (issue repeated below). Currently blocking our pipelines.
Looks like this was fixed and merged into main but never released. Can we please get this new version out to npm asap?

> When running npm audit, we get following error :
> 
> axios  0.8.1 - 1.5.1
> Severity: moderate
> Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
> fix available via `npm audit fix --force`
> Will install selenium-standalone@9.0.5, which is a breaking change
> node_modules/selenium-standalone/node_modules/axios
>   selenium-standalone  >=9.0.6
>   Depends on vulnerable versions of axios
>   node_modules/selenium-standalone
> 
> 2 moderate severity vulnerabilities
> Upgrading axios to 1.x in selenium-standalone would fix this issue.

**Comment by christian-bromann** [comment]
I just triggered a new release, it should be out any second.
