### ISSUE TITLE
Error downloading browser

### ISSUE THREAD

**Issue by marcelovani** [webdriverio/selenium-standalone#879]
## Expected Behavior
Download browser

## Current Behavior
Error
```
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.69/linux64/chromedriver-linux64.zip
Response code 404 (Not Found)
/home/selenium-standalone/lib/install.js:301
          throw new Error('Could not download ' + downloadUrl);
```

## Fix
I saw someone fixed this here https://github.com/webdriverio/selenium-standalone/compare/main...just-boris:selenium-standalone:main

**Comment by christian-bromann** [comment]
@marcelovani this has been fixed and released in [`v9.3.3`](https://github.com/webdriverio/selenium-standalone/commit/ab8f5631200225363643cf0f777c2d97a28fa41c)
